name = "backend"
compatibility_date = "2023-12-01"

[dev]
port = 8787

[vars]

SECRET= "aNKVaj0BhapmuvfwHf1KW0ZJ9yQ/mlFcMLQoS6SzRtA="
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmQ0MTY5MmItYmZlYi00OTU1LWEwMGYtNWY5MWMwZjBhZjQyIiwidGVuYW50X2lkIjoiYjViYjllZGRjZDNjOTBmOTMzZjI5NzI3ZTBlZmYxOGFiYjE1NzM2MWI2NDBiZWUzYzhhNDNlNjA5YWZkYmM0NiIsImludGVybmFsX3NlY3JldCI6IjZmZjUxNGVhLWVlZGItNDYyMy04YjFjLWJmN2E5MjY1OGJmNCJ9.x-3fCfiHu3Mew89yS-grwYyX-a0yE6S89XqwPiGSR54"


# DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWMyOWI0ZjctYTViNi00NDBkLThjOWUtZDk4NGVlM2RmYmIwIiwidGVuYW50X2lkIjoiYjExMzI4MjQ3ZWQ0MWJlMDliY2I3M2M2YjU3MWM2NTA4M2JhNTkyZDM1ZDExMDg1MTU3ZGU3NjJhYzU5MjE3NCIsImludGVybmFsX3NlY3JldCI6ImM3OTBjMGFlLTJkMmMtNDAyZC1iYWZlLTY1NjI3ZjBjMTVkZCJ9.IiGcpoYV-qlGqe4FshRC08VPjUc78_75GUpBHvx4dpc"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"